#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

wclean libso phaseChangeThreePhaseMixtures
wclean libso incompressibleThreePhaseMixture
wclean libso threePhaseMixture

wclean


#------------------------------------------------------------------------------
